# Generated by Django 3.2.13 on 2022-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220628_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.BooleanField(),
        ),
    ]
